### ISSUE TITLE
Error when starting without editing any files.

### ISSUE THREAD

**Issue by romans127** [nuxt-community/starter-template#1]
Greetings,

I receive the following error just after running the following commands : 
`vue init nuxt/starter`
`yarn`
`npm run dev`

```
vue.runtime.common.js:519[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
```

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c1">#c1</a>)</em></sub></div>

**Comment by alexchopin** [comment]
Hi,

It should be fixed now, you can re-install it.

Sorry about that :/

**Comment by romans127** [comment]
No worries thank you for the fast reply.  You guys are doing an amazing
job.  I'm hoping to contrubute once i get up to speed
