### ISSUE TITLE
Npm run build breaks on Windows 10

### ISSUE THREAD

**Issue by elektracodes** [nuxt-community/starter-template#10]
Hello, 

I cloned the starter git, run npm install and dev just fine. The project works exactly like the demo. 
When I try the npm run build command I get this error 

`ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":0,"remove":true}!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-121a11e9!./assets/css/main.css` 
```
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (C:\node\nu\node_modules\extract-text-webpack-plugin\loader.js:26:9)
 @ ./.nuxt/App.vue 3:0-192
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
```

This error appear 6 times on different areas of the project.
Why does this error appear? I try to see the if extract-text-webpack-plugin is called anywhere in the project, but I can't seem to find it. I have not edit any code, this happen to me with the cloned template.

I noticed that on the package.json the extract-text-webpack-plugin is not installed so I installed it as a dependency, but the error persists. 

Any help is appreciated.

OS: Windows 10
node: 7.4.0
npm: 4.1.2

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c14">#c14</a>)</em></sub></div>

**Comment by appsparkler** [comment]
@elektracodes can you check this file `./assets/css/main.css`.  There might be some **issue** in this file which is causing this error.

**Comment by elektracodes** [comment]
@app-sparkler Thank you for checking out the issue. 

Unfortunately is not a nuxt/starter issue but a nuxt issue like the one posted [here ](https://github.com/nuxt/nuxt.js/issues/170)

I have the the setup that worked for them, but on my machine it doesn't. As I understand is related to node/npm versions. I will not follow the issue anymore, since I decided to not use nuxt in the end. 

Thank you for your time.

**Comment by appsparkler** [comment]
Hi @elektracodes can you go ahead and `close` this issue in that case.

Thanks
