### ISSUE TITLE
Pre Loading

### ISSUE THREAD

**Issue by appsparkler** [nuxt-community/starter-template#16]
Hi @Atinux 

Is there a way I can achieve the pre-loading effect (on visiting the link) for the Nuxt application?

[http://smallenvelop.com/demo/simple-pre-loader/](http://smallenvelop.com/demo/simple-pre-loader/)

Thanks,
Akash

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c10">#c10</a>)</em></sub></div>

**Comment by atinux** [comment]
@appsprklr you can do it by rendering the loader and then using the `mounted` hook from Vue.js to load your data, but be aware that it won't be SSR.
