### ISSUE TITLE
yarn run dev bombs when adding CSS

### ISSUE THREAD

**Issue by 1stevengrant** [nuxt-community/starter-template#19]
Adding Bootstrap and a Google font to the `nuxt.config.js` causes the dev build to bomb.

```
{ rel: 'stylesheet', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css'},
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Work+Sans:400,700,900' }
```

Error is 
```
* ... in ./~/nuxt/~/vue-loader/lib/template-compiler?{"id":"data-v-5d918b31","preserveWhitespace":false}!./~/nuxt/~/vue-loader/lib/selector.js?type=template&index=0!./pages/index.vue
```

even though I added `vue-loader` as a dependency.

Any ideas why?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c16">#c16</a>)</em></sub></div>

**Comment by atinux** [comment]
It should work with the last version of nuxt.js :)
