### ISSUE TITLE
static pages generated don't work

### ISSUE THREAD

**Issue by sanxing-chen** [nuxt-community/starter-template#2]
It is normal when I use `npm run dev` or `npm run build` and `npm run start`, but it's abnormal when I use `npm generate` to generate static pages. The page appear and disappear quickly just leaving the footer. 
Did I do something wrong or it's a bug.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c4">#c4</a>)</em></sub></div>

**Comment by alexchopin** [comment]
Hi, 
Sorry, it was a bug but it's fixed now with the 0.9.2.

**Comment by sanxing-chen** [comment]
Sorry, I believe that I have downloaded the latest version. And it works normally on [my server](http://sxing.xyz:3691/), but abnormal on [github page](http://editor.sxing.xyz/). It appears normal sometimes but if you refresh the page, It will disappear. And I try in chrome's anonymous, I can work normally. I guess if something like cache make browser confused.

**Comment by atinux** [comment]
Actually it works nice on my computer @STayinloves 

But indeed, it's a cache problem, we are working on it for the 1.0, Nuxt will generate unique filename to avoid cache issue on CDN.

**Comment by sanxing-chen** [comment]
Thank you, look forward to it.

2016-12-24 18:33 GMT+08:00 Sébastien Chopin <notifications@github.com>:
