### ISSUE TITLE
eslint-loader save as devDependencies cause build failed in production environment

### ISSUE THREAD

**Issue by AvailCat** [nuxt-community/starter-template#22]
Reproduce step:
1. Init from this template
2. run `export NODE_ENV=production` 
3. run `npm run build` 

Set `NODE_ENV` to `production` will prevent npm install devDependencies, but the `eslint-loader` is required as a pre-loader during build process

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c15">#c15</a>)</em></sub></div>

**Comment by atinux** [comment]
Hi @Meeeeow 

It's now fixed, sorry for the delay: https://github.com/nuxt-community/starter-template/commit/fe69ec5b8d0268db823a49bc0536d6301231d55e
