### ISSUE TITLE
npm run dev fails on blank project

### ISSUE THREAD

**Issue by andreliem** [nuxt-community/starter-template#26]
Hey Guys,

I was just trying out the starter-template today and it doesn't seem to work for me. Not sure if this is specific to my setup, but it used to work.

When I run `npm run dev` I get this

```
/.../node_modules/nuxt/bin/nuxt-dev:11
const { Nuxt, Builder } = require('../')
      ^

SyntaxError: Unexpected token {
```

Seems like it might be something to do with babel?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c13">#c13</a>)</em></sub></div>

**Comment by andreliem** [comment]
Oh it's okay, it was because of my version of `node` that I was running.

**Comment by alejosv** [comment]
The version shoud be node 6 or later
