### ISSUE TITLE
Updating the used template later

### ISSUE THREAD

**Issue by ducdebreme** [nuxt-community/starter-template#30]
I started a test nuxt project some weeks ago. Run into some issues and discovered that my nuxt version is quite old (nuxt 1.0.0-alpha.5).

Question: is there a way to update the nuxt version of current project?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c19">#c19</a>)</em></sub></div>

**Comment by atinux** [comment]
Hi @ducdebreme 

Sure, you can use [npm-check-updates cli](https://www.npmjs.com/package/npm-check-updates) for this, or simply run `npm update --save` (see [npm doc](https://docs.npmjs.com/cli/update)) or `yarn upgrade`
