### ISSUE TITLE
Support separate dev and production config

### ISSUE THREAD

**Issue by thangman22** [nuxt-community/starter-template#31]
As original Vue.js build file is separate between development and production. Can we do in in nuxt.js template?

**Solution**

- Create 2 config file dev and production
- import 2 file in nuxt.config.js
- use merge to combine config follow env

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c22">#c22</a>)</em></sub></div>

**Comment by thangman22** [comment]
If you accept this Idea I will try to open Pull request

**Comment by atinux** [comment]
Hi @thangman22 

Actually Nuxt.js handle the dev vs prod webpack configuration automatically for you (`nuxt dev` and `nuxt build`).

Into your `nuxt.config.js`, I recommend you to use environment variables in production to update some values directly inside the file, this is actually a best-practice :)
