### ISSUE TITLE
Optional ES Lint?

### ISSUE THREAD

**Issue by shshaw** [nuxt-community/starter-template#32]
I wanted to try Nuxt out for a project, so I went with the starter template to get up & running fast.

Unfortunately, "fast" prototyping went out the window because ES Lint kept getting on to me about spaces and formatting. We could all stand to code a little cleaner, but the configuration meant that I couldn't get my code running until I formatted it how ES Lint demanded.

Not knowing enough about ES Lint to be able to disable it effectively and unable to find any information in the docs regarding it, I had to abandon using Nuxt in the interest of saving time to get something deployed.

Digging into it more now, I see that I probably could've removed the ES lint part of the nuxt.config.js, but none of this was really clear in my first introduction to Nuxt.

I'm also aware of the `/* eslint-disable */` comment option, but that had to be done in every file.

Ideally there should be a configuration option (just like in the [Vue webpack template](https://github.com/vuejs-templates/webpack)) to add ES Lint so Nuxt can be easily up & running without an ES Lint requirement.

Alternatively, some documentation on how to disable ES lint would be helpful!

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c27">#c27</a>)</em></sub></div>

**Comment by atinux** [comment]
Hi @shshaw 

I see, we will add a question into the installation to activate or no ES Lint.

**Comment by atinux** [comment]
You may want to use https://github.com/nuxt-community/create-nuxt-app now :)

**Comment by shshaw** [comment]
Thanks, @Atinux. I'll give that a whirl on the next fitting project 👍
