### ISSUE TITLE
Description should be escaped

### ISSUE THREAD

**Issue by OmgImAlexis** [nuxt-community/starter-template#39]
For example I added a description of `Twistly's Frontend` which caused this in the `nuxt.config.js`.

```
{ hid: 'description', name: 'description', content: 'Twistly's Frontend' }
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c28">#c28</a>)</em></sub></div>

**Comment by atinux** [comment]
It's related to vue-meta directly.
