### ISSUE TITLE
Live eslint

### ISSUE THREAD

**Issue by appsparkler** [nuxt-community/starter-template#4]
## Enhancement

Currently, the `nuxt/starter` doesn't have `live eslint` as seen with the `vue-cli webpack template`.  I was able to implement something which provides this feature for the `vue-cli nuxt/starter template` 

### First install `eslint-loader` (all other packages are available in nuxt/starter)
`npm i -D eslint-loader`

### Next, update the nuxt.config.js to include preLoaders (`enforce: 'pre'`)

```
//nuxt.config.js
// in webpack2.2, we have enforce: 'pre' instead of preLoaders
...
build: {
    ...
    // EXTEND
    extend (config, { isClient }) {
      if (isClient) {
        config.module.rules.push({
            enforce: 'pre',
            test: /\.js$/,
            loader: 'eslint-loader',
            exclude: /(node_modules)/,
        },{
            enforce: 'pre',
            test: /\.vue$/,
            loader: 'eslint-loader',
            exclude: /(node_modules)/,
        })
      }
    }
  },
...

```
Now, you should have `live eslint`

Ref : https://github.com/nuxt/nuxt.js/issues/212

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c5">#c5</a>)</em></sub></div>

**Comment by atinux** [comment]
It's now added on the starter, see https://github.com/nuxt/starter/commit/8719d451a0c6ab32ea6da71c94519de1694c675c

Thank you @app-sparkler

**Comment by tiagomatosweb** [comment]
Hi, sorry but I just installed the starter template, everything went well.
But, I save files and eslint doesn't pick up any error. However, if I run npm run lint it does.

Any idea?

**Comment by tiagomatosweb** [comment]
I ended up figuring out.
The parameter is wrong in extend. It should be ctx.dev instead ctx.isDev

```
extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
```

**Comment by atinux** [comment]
Nice, thank you @tiagomatosweb :)

Fixed, see https://github.com/nuxt-community/starter-template/commit/1d6eda62b8ab20e7960b08b2f131d4b7d4af9c84
