### ISSUE TITLE
Add eslint-plugin-vue

### ISSUE THREAD

**Issue by apertureless** [nuxt-community/starter-template#41]
May be a good idea to add [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) for more consistent and clean code style

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c20">#c20</a>)</em></sub></div>

**Comment by atinux** [comment]
Done :)
