### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-runtime" 

### ISSUE THREAD

**Issue by bdougie** [nuxt-community/starter-template#5]
I run the cli command init this started and run `npm run dev` or `nuxt generate` and get the same error

Unknown plugin "transform-runtime" 

I will add a PR to add a .babelrc since that is all it needs

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c3">#c3</a>)</em></sub></div>

**Comment by atinux** [comment]
What version of node.js do you have and npm?

Also, what version of nuxt.js is installed?
`cat node_modules/nuxt/package.json`

**Comment by bdougie** [comment]
using node v7.0.0
npm v3.10.8
nuxt@0.9.8 but my package.json is set to latest 
https://github.com/bdougie/nuxt-starter/blob/master/package.json

**Comment by atinux** [comment]
It's really weird, I just tried with your repository (I removed the .babelrc) and it works perfectly:

![nuxt](https://cloud.githubusercontent.com/assets/904724/22841676/c7859df6-efd2-11e6-90e2-9f8dfd4a4be1.gif)

Can you try to remove the `node_modules` folder and try to install it via `yarn install`?

**Comment by bdougie** [comment]
That is weird, might be my environment. I will look into it later tonight

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/5713670/22844066/2e312c2e-ef91-11e6-81c2-34cd4368ea7d.gif)

**Comment by demyan1411** [comment]
I have the same Error, please help
