### ISSUE TITLE
How about update .gitignore ?

### ISSUE THREAD

**Issue by limichange** [nuxt-community/starter-template#50]
Like this https://github.com/github/gitignore/blob/master/Node.gitignore

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c25">#c25</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
From my point of view, it's not necessary.
the current `.gitignore` has enough rules in agreement with a standard Nuxt project.

Then, after create your project from vue-cli, you can custom your `.gitignore` as you wish.

In addition, you can to push your global rules  in your global `.gitignore` config:
https://help.github.com/articles/ignoring-files/#create-a-global-gitignore
https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

**Comment by limichange** [comment]
I like your answer. 👍
