### ISSUE TITLE
Typing in page url does not work

### ISSUE THREAD

**Issue by jzucadi** [nuxt-community/starter-template#53]
Typing in the direct url of a page or section of the website does not work. When I try this I get sent to the homepage but without any of my data loaded from my async calls. It works fine in dev setup, but when I push the site live on static hosting I run into this problem

Is there any way to enable direct links so users can navigate to different sections of the website without going to the homepage first?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c26">#c26</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Please share some source code ou your github repository.
I don't understand your question.

If it's your first application,
Read the Nuxt.js documentation "[Starting from scratch](https://nuxtjs.org/guide/installation#starting-from-scratch)",
then check this  simple example project: https://github.com/nuxt/nuxt.js/tree/dev/examples/hello-world

**Comment by jzucadi** [comment]
I don't need help reading the getting started documentation or looking at how to do "hello world".
