### ISSUE TITLE
How to start Nuxt starter-template in production with PM2

### ISSUE THREAD

**Issue by PhouvanhKCSV** [nuxt-community/starter-template#54]
Hi
i would like to know how to run Nuxt app (starter-template) with PM2,

I can run it with "npm run start" but i dont know how to run it with PM2.

Thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c34">#c34</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
read my answer here: https://github.com/nuxt/nuxt.js/issues/1541

**Comment by PhouvanhKCSV** [comment]
Thank you NicoPennec
