### ISSUE TITLE
页面无法运行起来

### ISSUE THREAD

**Issue by 18210942958** [nuxt-community/starter-template#55]
会报invalid name:"name"页面无法运行起来

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c31">#c31</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
In english please :)
and we need more details to help you...
give us steps to reproduce

**Comment by ghost** [comment]
检查一下你安装的nuxt版本，如果是1.0.0以上，本地需要安装的node版本是8.0以上
