### ISSUE TITLE
should this be updated to include a newer version of Nuxt?

### ISSUE THREAD

**Issue by dimitrieh** [nuxt-community/starter-template#57]
https://github.com/nuxt-community/starter-template/blob/308ca01d6520629dab11316b9717a68fd106c844/template/package.json#L16

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c35">#c35</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
It's not necessary with the [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) (`^` notation)
npm will install the lastest version 

`^1.0.0` is equal to `>= 1.0.0 < 2.0.0`

**Comment by dimitrieh** [comment]
@NicoPennec great, thanks for that bit of information!
