### ISSUE TITLE
new version nuxt

### ISSUE THREAD

**Issue by borodadada** [nuxt-community/starter-template#63]
hello, how update template that i use new version nuxt? in npm install nuxt 1.0.0

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c41">#c41</a>)</em></sub></div>

**Comment by HoraceKeung** [comment]
In package.json, find:
```
"dependencies": {
    "nuxt": "^1.0.0"
  }
```
Change it so it is `"nuxt": "^1.4.0"`
Then do npm install

**Comment by NicoPennec** [comment]
duplicate https://github.com/nuxt-community/starter-template/issues/57
