### ISSUE TITLE
Can't do nothing with starter template

### ISSUE THREAD

**Issue by YuriiNskyi** [nuxt-community/starter-template#65]
### Version

[1](https://github.com/nuxt-community/starter-template/releases/tag/1)

### Reproduction link

[https://nuxtjs.org/guide/installation](https://nuxtjs.org/guide/installation)

### Steps to reproduce

Follow the steps from https://nuxtjs.org/guide/installation, section Using Nuxt.js starter template.

### What is expected ?

Successfully run template

### What is actually happening?

E:\TestProjects\vuenuxt\my-test-project\node_modules\nuxt\lib\core\module.js:14
  async ready() {
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\TestProjects\vuenuxt\my-test-project\node_modules\nuxt\lib\core\index.js:2:16)
    at Module._compile (module.js:571:32)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! my-test-project@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-test-project@1.0.0 dev script 'nuxt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-test-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-test-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-test-project
npm ERR! There is likely additional logging output above.

### Additional comments?

My OS is Windows 10.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c43">#c43</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Node v8.x is mandatory (cf. [prerequisites](https://github.com/nuxt-community/starter-template#prerequisites))
You are currently on Node v7.4.0

Please upgrade to the latest Node.js v8.11 LTS version => https://nodejs.org/en/
