### ISSUE TITLE
Same port error ('EADDRINUSE') when running multiple projects

### ISSUE THREAD

**Issue by jpoechill** [nuxt-community/starter-template#66]
### Version
starter-template

### Reproduction link
NA

### Steps to reproduce
create first project with vue-cli, install packages, and run dev
create second project with vue-cli, install packages, and run dev

### What is expected?
Both projects should be ran without error

### What is actually happening?
Same port error, 'Error: listen EADDRINUSE 127.0.0.1:3000'

1st project occupies port, while 2nd project attempts to connect to same one

### Additional comments?
This could be solved manually, though it is tedious. In previous versions of Vue, etc., ports are reconfigured automatically.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c44">#c44</a>)</em></sub></div>

**Comment by Extarys** [comment]
In dev it might be good. I personally prefer static port though as they are predictable.
But for prod it would be a nightmare :laughing: 
I think the Nuxt team would prefer fixing bug and implementing more modules than adding such functionality as it could easily be 'fixed' by modifying the port manually as a workaround.

Maybe someone on the team could take note of the suggestion though :smile_cat:
