### ISSUE TITLE
Progress bar config

### ISSUE THREAD

**Issue by appsparkler** [nuxt-community/starter-template#7]
Hello @Atinux, if possible, please clarify this issue.  Maybe i'm doing something wrong due to which the `progress bar` is _persistent_ even when i'm setting `loading: false`.

Though i have set the `loading: false` as mentioned [here](https://nuxtjs.org/api/configuration-loading#disable-the-progress-bar) the `progress bar` is still visible on the `webapp`.

![image](https://cloud.githubusercontent.com/assets/12084821/22871083/96e58672-f1d3-11e6-9a9d-fb5395e3a719.png)

![image](https://cloud.githubusercontent.com/assets/12084821/22871094/ae1a7a82-f1d3-11e6-89d2-b0816ace8680.png)

Please suggest what can be done to avoid the `progress bar` in the `app`.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c6">#c6</a>)</em></sub></div>

**Comment by atinux** [comment]
I just tried and it works perfectly.

Did you restart the server with `npm run dev`?
