### ISSUE TITLE
module build failed

### ISSUE THREAD

**Issue by Rush-YL** [nuxt-community/starter-template#82]
Module build failed (from ./node_mdules/eslint-loader/index.js): TypeError: Cannot read property 'eslint' of undefined at Object.module.exports

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/starter-template/issues/c57">#c57</a>)</em></sub></div>

**Comment by aeksco** [comment]
**10/23/18 Edit**: the comment below is incorrect - apologies for misleading anyone! 

~@Rush-YL~

~Remove `ctx.isClient` and replace with `process.client` in `nuxt-config.js`:~

```js
extend (config, { isDev }) {
  if (isDev && process.client) {
	config.module.rules.push({
	  enforce: 'pre',
	  test: /\.(js|vue)$/,
	  loader: 'eslint-loader',
	  exclude: /(node_modules)/
	})
  }
}
```

[Source](https://github.com/nuxt/nuxt.js/issues/3216#issuecomment-380777572)

**Comment by Codefa** [comment]
`extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }`

**Comment by Codefa** [comment]
Do this Way in nuxt.config.js

`extend (config, ctx) {
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }`

**Comment by Thomas-Philippot** [comment]
> @Rush-YL
> 
> Remove `ctx.isClient` and replace with `process.client` in `nuxt-config.js`:
> 
> ```js
> extend (config, { isDev }) {
>   if (isDev && process.client) {
> 	config.module.rules.push({
> 	  enforce: 'pre',
> 	  test: /\.(js|vue)$/,
> 	  loader: 'eslint-loader',
> 	  exclude: /(node_modules)/
> 	})
>   }
> }
> ```
> 
> [Source](https://github.com/nuxt/nuxt.js/issues/3216#issuecomment-380777572)

Had the same issue and actually it worked !

**Comment by XanderLuciano** [comment]
@aeksco This is incorrect and `process.client` will be undefined.

**Comment by NicoPennec** [comment]
this issue is fixed by the following PR: https://github.com/nuxt-community/starter-template/pull/86

please, don't apply the @aeksco's proposal !

**Comment by aeksco** [comment]
@XanderLuciano @NicoPennec Apologies for the misleading comment - I've updated my post directing people not to follow those instructions. Thanks for posting about the fix :)
