### ISSUE TITLE
BeforeMount function is executing **before** page transition too...

### ISSUE THREAD

**Issue by appsparkler** [nuxt-community/starter-template#9]
@Atinux, if possible, please look into this.  I don't know if it is a **bug** or it is working **as expected**.

## # Isolating this issue
- Create two layouts - `default` and `other`
- Create two pages - `pages/index.vue` and `pages/about/index.vue`
- Set `layout: 'other'` on the `pages/about/index.vue` page
- Add `beforeMount event function` to both the pages with `console.log('Before mounting :pageName page')`

#### *checkout `issue-branch` after `cloning` the `repo`. 
```
// CLONE app-sparkler/nuxt-starter
$ git clone https://github.com/app-sparkler/nuxt-starter

// CHECKOUT issue-branch
$ git checkout issue-branch

// INSTALL with yarn or npm
$ yarn install
OR
$ npm install

// RUN dev server
$ npm run dev
```

Thanks,
Akash
 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c8">#c8</a>)</em></sub></div>

**Comment by atinux** [comment]
Hi @app-sparkler 

This is related to https://github.com/nuxt/nuxt.js/issues/214, it will be fixed in the next release 👍
